### ISSUE TITLE
Readme resource too lager leads to a slow clone

### ISSUE THREAD

**Issue by SuperY** [Jiar/SegementSlide#1]

**Comment by Jiar** [comment]
I'm sorry for that, but I haven't found a better tool to optimize GIF sizes.

**Comment by SuperY** [comment]
I download master zip, the main folder is 90.3M, but Snapshots folder size 88.7M ...

**Comment by SuperY** [comment]
Why not put Snapshots files on the third cloud storage?
The mp4 files are unnecessary.

**Comment by Jiar** [comment]
I will move Snapshots folder to another repository, Thanks. 😊

**Comment by SuperY** [comment]
Just remove Snapshots with a normal commit may not work. 
You should remove cache of these files from the repository.
[Removing files from a repository's history.](https://help.github.com/articles/removing-files-from-a-repository-s-history/)
The clone will be quicker.

**Comment by Jiar** [comment]
I haven't tried it. I need to spend some time.

**Comment by Jiar** [comment]
I had rewritten commits to remove big resource folder.

Thank you for your advice! 😋@SuperY
