### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fsresponser** [Jiar/SegementSlide#10]
scrollView.observe(\.contentOffset, options: [], changeHandler: {  }
这种方法在iOS10会crash，有好的解决办法？

**Comment by fsresponser** [comment]
scrollViewDidScroll 都不调用？

**Comment by Jiar** [comment]
感谢反馈！

我这边测试下来，一直没有发现因为该方法导致的闪退问题。可以的话，你可以附上截图让我看下。

另外，
> scrollViewDidScroll 都不调用？

指的是`func scrollViewDidScroll(_ scrollView: UIScrollView, isParent: Bool)`方法没有调用？

**Comment by fsresponser** [comment]
崩溃是因为iOS10被观察者生命周期变窄。

**Comment by fsresponser** [comment]
scrollViewDidScroll 都不调用？是指原生的scrollview代理方法

**Comment by fsresponser** [comment]
![image](https://user-images.githubusercontent.com/8423149/55047626-5d212500-5080-11e9-9259-275548afc65b.png) crash的地方

**Comment by Jiar** [comment]
是不是收到类似如下的报错提示？

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An 
instance 0x7f9e200b8400 of class SegementSlide.SegementSlideScrollView was deallocated while 
key value observers were still registered with it. Current observation info: 
<NSKeyValueObservationInfo 0x618000224860> (
<NSKeyValueObservance 0x61800024d920: Observer: 0x61800024c2a0, Key path: contentOffset, 
Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x600000045070>
)'
```

**Comment by Jiar** [comment]
能否贴一下你那边的报错信息呢

**Comment by fsresponser** [comment]
就是上面的信息

**Comment by Jiar** [comment]
好的，我尝试着去修复了这个问题。你可以试试看最新的`2.1.1`版本是否还存在这个问题。

**Comment by fsresponser** [comment]
![image](https://user-images.githubusercontent.com/8423149/55697341-9c8e3080-59f3-11e9-8099-793db4fada50.png) 发现一个crash, 知道这是崩在哪儿了吗

**Comment by Jiar** [comment]
光是这条信息不够判断。
