### ISSUE TITLE
父子容器滚动冲突

### ISSUE THREAD

**Issue by susuyan** [Jiar/SegementSlide#14]
问题1：
 在 header 中添加了一个横向滚动的 UICollectionView
 横向滚动时，会触发 下面 tab的滚动，UICollectionView 不能响应事件
 想问一下这种情况，使用的正确姿势
问题2：
 分页的一个子控制器，当数据源为空的时候，tab 悬浮之后，子控制器就不能滚动交互了

**Comment by Jiar** [comment]
感谢反馈。

问题1:
- 这种情况是会有的，导致这样的原因是我在`headerView`中重写了`hitTest`方法，原先希望通过重写该方法，达到『在`headerView`上进行滚动，也有父子`scrollView`联动的效果』，但是目前看来，做得还不够好，尤其对于你这种情况。
- 你可以尝试在使用本地pod依赖，注释掉`headerView`中的`hitTest`方法，这样你的`UICollectionView `滚动应该不会有问题了，不过同时，也无法在`headerView`上使得父子`scrollView`联动了。这是个临时方法。
- 这里同时也是需要优化的点，目前没有找到更合适的方式来处理。

问题2:
推测导致这个问题的原因是：子控制器的`scrollView`中没有内容，导致`scrollView`的`didscroll`方法没有调用导致的。

**Comment by susuyan** [comment]
谢谢回复
