### ISSUE TITLE
Using without slideSwitcherView.

### ISSUE THREAD

**Issue by lm2343635** [Jiar/SegementSlide#18]
I do not have multiple content view controllers. 
For this reason, is there any way to use this library without using slideSwitcherView.

The top is a view and the bottom is a tableView.

Thanks!

**Comment by Jiar** [comment]
Thanks for feedback!

Sorry for that, SlideSwitcherView is coupled with SegementSlide currently.

However, there is a plan to pull the subcomponents(SegementSlideSwitcherView, SegementSlideContentView) of SegementSlide out of the way and provide them as delegate.

**Comment by HParis** [comment]
@lm2343635 

```
    override var switcherHeight: CGFloat {
        return 0
    }
```

Maybe this can help you.

**Comment by Jiar** [comment]
@HParis Thank you, It seems resolved, I will close this issues.
