### ISSUE TITLE
请问怎么实现storyboard页面来回

### ISSUE THREAD

**Issue by laohanme** [Jiar/SegementSlide#2]

**Comment by Jiar** [comment]
`storyboard`页面来回？指的是`storyboard`中的各个`UIViewController`之间跳转吗？

**Comment by laohanme** [comment]
对， 不好意刚刚初步进入领域 有些方面表达的不是很专业 请见谅

**Comment by Jiar** [comment]
`storyboard`中的各个`UIViewController`之间跳转跟这个库没有直接关系，不太了解的话，可以看下这里[iOS - Push viewController from code and storyboard](https://stackoverflow.com/questions/13987026/ios-push-viewcontroller-from-code-and-storyboard)。

如果是想在`storyboard`或者`xib`中使用`SegementSlide`的话，让你自定义的`UIViewController`继承`SegementSlideViewController`或是`TransparentSlideViewController`即可。

**Comment by laohanme** [comment]
好的谢谢您 Jiar 我会自行研究研究下
