### ISSUE TITLE
Empty TableView issue.

### ISSUE THREAD

**Issue by hayabusabusa** [Jiar/SegementSlide#21]
Thanks for this great library :)
When child TableView is empty and header view is completely hidden, i can swipe up but can't swipe down.
Can i disable swipe up gesture or enable swipe down gesture when child TableView is empty ?

**Comment by Jiar** [comment]
Thanks for feedback!

- I am sorry for that, you can not disable swipe gesture now.
- I suggest you to provide an empty cell, so you can swipe down the header view.

**Comment by hayabusabusa** [comment]
@Jiar Thanks for response!
> I suggest you to provide an empty cell, so you can swipe down the header view.  

This solution is the best now. I will try!
