### ISSUE TITLE
在某些场景下会触发：无法将 headerView 继续下滑

### ISSUE THREAD

**Issue by alflix** [Jiar/SegementSlide#22]
Hi，关注 SegementSlide 挺久了，最近在使用过程中发现了一个 bug，某些场景下：无法将 headerView 继续下滑。例如：下面是一个使用场景：

将 headerView 滑倒至 headerView 隐藏状态，点击进入二级页面，重新回来，就会出现：

![Kapture 2019-07-08 at 21 58 01](https://user-images.githubusercontent.com/4870617/60816150-a9294d00-a1cb-11e9-8fff-a6ac35a4eeb3.gif)

不知有什么解决方法？

**Comment by alflix** [comment]
找到原因了，原因是 reloadData 的时候会触发其他 SegementSlideViewController 调用 willClearAllReusableViewControllers(), willClearAllReusableViewControllers 会把 childKeyValueObservation 置为 nil，

<img width="1575" alt="Screen Shot 2019-07-08 at 11 48 35 PM" src="https://user-images.githubusercontent.com/4870617/60824020-6f604280-a1db-11e9-9b14-89af985bcb50.png">

而 childKeyValueObservation 是需要在调用

```swift
public func segementSlideContentView(_ segementSlideContentView: SegementSlideContentView, didSelectAtIndex index: Int, animated: Bool)
````
 时才会初始化的，

<img width="1577" alt="Screen Shot 2019-07-08 at 11 49 02 PM" src="https://user-images.githubusercontent.com/4870617/60824004-696a6180-a1db-11e9-96b2-1b3e92f5358d.png">


这就导致了上叙场景出现问题。

**Comment by Jiar** [comment]
感谢反馈！

我了解你说的问题了，不过我没猜错的话，你应该是在`master`分支上发现这个问题的吧。在`v2`分支上，我前一阶段已经修复了这个问题，只是还没有发布新版本。你可以尝试下最新的`v2`分支上是否还存在这个问题。

**Comment by alflix** [comment]
感谢，期待新版本发布。

**Comment by Jiar** [comment]
新版本已发布 [version 2.2](https://github.com/Jiar/SegementSlide/releases/tag/2.2)
