### ISSUE TITLE
导航栏隐藏时, segementSlideSwitcherView 对刘海屏的适配

### ISSUE THREAD

**Issue by wanqingrongruo** [Jiar/SegementSlide#26]
Hello,
非常感谢作者提供这么优秀的组件... swift 代码风格 very elegant..hahaha
在学习源码的时候遇到了一个问题,对于刘海屏, 当我隐藏导航时, 刘海完全依赖下面的视图颜色,这 样体验不太好...如果 segementSlideSwitcherView 变化去适应刘海屏可能会更好

**Comment by Jiar** [comment]
感谢反馈！

推测你遇到的问题，应该是基于继承`TransparentSlideViewController`实现的界面。`TransparentSlideViewController`继承自`SegementSlideViewController`实现，提供了一套通用式的导航栏样式的处理，这种处理未必适用于所有情况。隐藏导航栏的话，确实可能会导致`TransparentSlideViewController`出现一些视觉上的问题。针对这种情况，我更建议继承`SegementSlideViewController`来实现对导航栏的处理，以满足需求。

**Comment by wanqingrongruo** [comment]
感谢回复...
这边我会自己处理...
我会把 整个 `segementSlideSwitcherView` 抽一个协议出来, 只用遵从协议显示一个 view 可以做 替代 `segementSlideSwitcherView`...
给 `segementSlideSwitcherView` 提供整体自定义的空间
issue 我就关闭了
谢谢了,比心

**Comment by Jiar** [comment]
👍
