### ISSUE TITLE
感觉这个demo写的太复杂了，增加了阅读难度

### ISSUE THREAD

**Issue by wuyang1314** [Jiar/SegementSlide#27]

**Comment by Jiar** [comment]
有点吧...不过是为了考虑更多的情况，最最基础的用法，就是`README.md`上的用法。

**Comment by wuyang1314** [comment]
哈哈，感觉还是要以讲解清楚为最佳啊，造轮子太麻烦了，像我这种菜鸟，如果你只给我看滑动的，我应该能看明白，这多了，我就晕了，看不明白了，我话太多了，楼主大大见谅呀

**Comment by Jiar** [comment]
不要紧。

**Comment by ameue** [comment]
@Jiar 如果一个页面有三个子控制器，其中两个子控制器里面是tableview布局，另一个是collectionView布局，这个collectionview是左右滑动的，可以支持吗？

**Comment by Jiar** [comment]
不好说，我估计会有手势冲突问题

**Comment by ameue** [comment]
要不搞一下？

**Comment by Jiar** [comment]
你可以多尝试尝试😉
