### ISSUE TITLE
SegementSlideSwitcherView add icon

### ISSUE THREAD

**Issue by AppleTTT** [Jiar/SegementSlide#29]
how can I add icon in SegementSlideSwitcherView if I don't want just show title

**Comment by Jiar** [comment]
Thanks for feedback!

This is not possible now, and the next step is to delegate the switch controler to developers so that they can use custom or other third-party switch controler.

**Comment by Jiar** [comment]
#18

**Comment by Jiar** [comment]
version 3 is released, It is support to use custom switcherView now.
