### ISSUE TITLE
继承终归不是一个好的选择

### ISSUE THREAD

**Issue by shaop** [Jiar/SegementSlide#3]
## WHY

如题，如果个别项目已经使用基础类，那是否就基本就告别该库了？

## HOW

可以抽离组建为单独的 View， 子的 ViewController 使用协议来控制属性。

另，子的 ViewController 也可以加入生命周期的控制。

**Comment by Jiar** [comment]
感谢反馈！

- 显然继承不是好的选择，之后会考虑用协议来更好地解耦，不过不会放在`2.0`这个版本。
- 另外对于『子的 ViewController 也可以加入生命周期的控制』这句话，我没能很好理解你的意思，可以的话，希望能解释一下。

**Comment by shaop** [comment]
hi !
关于「子的 ViewController 的生命周期」只是一个建议，因为页面之前的切换通常会涉及到一些生命周期的调用，更贴近于 UITabBarController 的体验，类似调用 `viewWillDisappear`, `viewWillAppear `等方法，可以设置变量控制。

> 目前公司项目中就有用到类似的方法。

使用下面的方法能在合适的位置进行控制

```objc
- (void)beginAppearanceTransition:(BOOL)isAppearing animated:(BOOL)animated;

- (void)endAppearanceTransition;
```

**Comment by Jiar** [comment]
不错的方式，我会考虑采用这种方式。👍
