### ISSUE TITLE
能添加一个设置scrollView的contentInset属性么

### ISSUE THREAD

**Issue by yd2008** [Jiar/SegementSlide#30]
如题，项目需求在scrollView下面有其他控件，故需要子scrollView要再能划上去点，我尝试直接设置子scrollView的contentInset但是发现没有效果。

**Comment by Jiar** [comment]
感谢反馈！

不过我应该没有对`contentInset`进行过调整，能否提供一个简单的demo来展示你的问题呢？

**Comment by yd2008** [comment]
谢谢作者解答 我已解决 是我自己地方设置不正确☺

**Comment by Jayxiang** [comment]
你怎么设置的这个
