### ISSUE TITLE
Tap to return to top not working consistently

### ISSUE THREAD

**Issue by danqing** [Jiar/SegementSlide#31]
iOS has this handy feature where if you tap the top of the screen, the scroll view goes all the way back to the top.

This works most of the time. However, if you scroll down and switch to a different tab, it doesn't work until you do some scrolling.

**Comment by Jiar** [comment]
Thanks for feedback!

It's most likely a bug, and I'll check and fix it. At the same time, you are also welcome to participate.

**Comment by Jiar** [comment]
Version `3.0.1` has been released and fixed the problem.
