### ISSUE TITLE
修改了segementSlideScrollView 约束后 contentSlideView 会滑不到底

### ISSUE THREAD

**Issue by wanqingrongruo** [Jiar/SegementSlide#33]
不清楚是不是 issue 30 想做点事情...
就是 想在 `SegementSlideViewController` 页面底下加一个固定在底部的按钮
```
segementSlideScrollView.snp.updateConstraints { (make) in
        make.bottom.equalToSuperview().offset(-PunchBottomView.totalHeight-safeAreaBottomLayoutGuide)
}
```
然后内部的 viewController 就滚动不到底部,应该是 内部的 contentScrollView frame 有问题
不知道具体应该操作哪些,咨询一下

**Comment by wanqingrongruo** [comment]
我找到问题了
```
 if segementSlideContentView.bottomConstraint == nil {
     segementSlideContentView.bottomConstraint = segementSlideContentView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
 }
```
关于 `segementSlideContentView` 底部约束有待商榷... 
它的父视图是 `segementSlideScrollView`.. 由于 scrollView 的性质, 你让 `segementSlideContentView` 底部约束直接与 当前 controller 的 view 相关联, 这就阻碍了 我重置 `segementSlideScrollView` 约束的可能性. 因此无论我怎么修改 `segementSlideScrollView` 约束, childViewController 内部的 scrollview frame 都会出错, 不能完全显示
我目前在 `SegementSlideViewController` 直接开放了一个属性 bottomPadding 用于子视图重写,返回对应的值, 来达到我的需求... 你看看是否需求在整体接口上修改
```
 open var bottomPadding: CGFloat {
     return 0
 }
```
```
if segementSlideContentView.bottomConstraint == nil {
    segementSlideContentView.bottomConstraint = segementSlideContentView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -bottomPadding)
}
```
thx

**Comment by Jiar** [comment]
感谢反馈！

- 在外部修改`SegementSlideViewController`的约束自然是不行的。
- 放出`bottomPadding`属性不是推荐的做法，可以模仿`headerView`的方式。
