### ISSUE TITLE
多次重设数据，滑倒顶部，无法下拉

### ISSUE THREAD

**Issue by yaofen** [Jiar/SegementSlide#35]
进入界面调 reloadData()刷新默认tab，然后网络tab数据数据回来，在次reloadData()刷新，把列表滑倒顶部，无法下拉。原因：clearAllReusableViewControllers() 重制了，但是selectedIndex没有重制，guard index != selectedIndex else { return }

**Comment by winterwd** [comment]
我也碰到类似的问题，当 contentView 内容过少的时候，滑动到顶部，无法下拉。

希望作者尽快修复这么多 issues，谢谢~

**Comment by Jiar** [comment]
感谢反馈！

已确认是bug，这几天内会修复并发版。

**Comment by Jiar** [comment]
2.2.4版本已发布并解决这个问题。：）
