### ISSUE TITLE
是否可以添加 下划线“依恋”样式(类似微博)

### ISSUE THREAD

**Issue by XavierLost** [Jiar/SegementSlide#39]
参考https://github.com/SPStore/SPPageMenu 有实现思路
样式更多
![IMG_79FEBB9DC06E-1](https://user-images.githubusercontent.com/24632295/68264738-d821d380-0084-11ea-8038-69c6d1251744.jpeg)

**Comment by Jiar** [comment]
感谢反馈！

`V3`版本正在开发，不出意外这周能完成开发并发版，届时会抽出`Switcher`控件，方便大家使用自定义的控件。😉

**Comment by Jiar** [comment]
`V3`已开发完成，请尝试使用。
