### ISSUE TITLE
两层嵌套的问题。

### ISSUE THREAD

**Issue by ameue** [Jiar/SegementSlide#40]
TransparentSlideViewController作为第一层包裹在最外层，第一个ContentViewController中是一个UIPageviewController，当page在切换的时候，怎么重载@objc optional var scrollView: UIScrollView { get }呢？

**Comment by anchao-lu** [comment]
外层内层都是 SegementSlideViewController，怎样在内层滑动到第一个或者最后一个segement，再次滑动的时候代理到外层的segement
