### ISSUE TITLE
感谢，我费劲千辛万苦才找到这个库

### ISSUE THREAD

**Issue by Gaozn** [Jiar/SegementSlide#43]
之前查找了到很多库，在contentView里如果使用了plain样式的tableView，上滑时就会导致sectionheader固定在一个位置。这个真的解决了我的问题。

**Comment by Gaozn** [comment]
请问一下，如何关闭header的手势，并且让系统的侧边滑动返回有效

**Comment by Jiar** [comment]
感谢反馈！

目前`Example`中的示例，是支持系统的侧边滑动返回的。

**Comment by i-tengfei** [comment]
> 目前`Example`中的示例，是支持系统的侧边滑动返回的。

我这里侧滑返回也是无效的，仔细在`Example`里找了半天也没发现有什么特殊设置

**Comment by i-tengfei** [comment]
哦，找到问题了，我覆盖了`leftBarButtonItem`，导致了侧滑返回无效，默认是可以的

**Comment by Jiar** [comment]
👌
