### ISSUE TITLE
有个小bug，无故重新布局

### ISSUE THREAD

**Issue by ascenx** [Jiar/SegementSlide#5]
我在自定义的 headerView 添加了一个 textField 和 label，监听 textField 的输入改变 label，结果 textField一输入，键盘就消失了。发现每次一输入完之后就重新布局了

```
    open override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        layoutSegementSlideScrollView()
    }
```
每次只要监听改变了label都会调用 SegementSlideViewController 的这个方法，注掉`layoutSegementSlideScrollView()`后就没问题了。操作并未改变高度，和其他布局，只改变了label的text.

**Comment by Jiar** [comment]
感谢反馈

一般来说，`headerView`上的操作，不会导致`SegementSlideViewController`中的`viewDidLayoutSubviews`方法被调用。不过，为了能让手势在`headerView`滑动也能让子`viewController`滚动，重写了`headerView`的`hitTest`方法。

你试试看注释掉`SegementSlideHeaderView`中的`hitTest`方法，看还会不会触发`SegementSlideViewController`的`viewDidLayoutSubviews`方法。或者在`hitTest`方法中打断点，看下是不是转发到子`viewController`的`scrollView`上去了。

另外，直接注释`viewDidLayoutSubviews`中的`layoutSegementSlideScrollView`是不可取的，会导致比如：提供的`Example`工程中首页`tab`的子`viewController`高度不对的问题。

**Comment by ascenx** [comment]
> 感谢反馈
> 
> 一般来说，`headerView`上的操作，不会导致`SegementSlideViewController`中的`viewDidLayoutSubviews`方法被调用。不过，为了能让手势在`headerView`滑动也能让子`viewController`滚动，重写了`headerView`的`hitTest`方法。
> 
> 你试试看注释掉`SegementSlideHeaderView`中的`hitTest`方法，看还会不会触发`SegementSlideViewController`的`viewDidLayoutSubviews`方法。或者在`hitTest`方法中打断点，看下是不是转发到子`viewController`的`scrollView`上去了。
> 
> 另外，直接注释`viewDidLayoutSubviews`中的`layoutSegementSlideScrollView`是不可取的，会导致比如：提供的`Example`工程中首页`tab`的子`viewController`高度不对的问题。

感谢回复。
注掉`SegementSlideHeaderView`中的`hitTest`方法仍然会触发。
如果不注释掉`viewDidLayoutSubviews`中的`layoutSegementSlideScrollView`，那注释掉
`SegementSlideHeaderView`中`config`方法中的

```
//        if let lastHeaderView = lastHeaderView {
//            lastHeaderView.removeAllConstraints()
//            lastHeaderView.removeFromSuperview()
//        }
```
这样也没问题，但是为什么会触发重新布局还是不清楚。

**Comment by Jiar** [comment]
方便的话，能不能将产生问题的部分代码单独弄成一个demo提供给我看下呢，只是目前这样的话，也不太清楚如何能更好地解决问题。

**Comment by Jiar** [comment]
收到你的邮件demo，已经在[2.0-beta-16](https://github.com/Jiar/SegementSlide/releases/tag/2.0-beta-16)中修复该问题。

**Comment by ascenx** [comment]
好的。我有点好奇是因为什么原因，能简单说明一下吗？

Jiar <notifications@github.com> 于2019年2月28日周四 下午6:44写道：

**Comment by Jiar** [comment]
这是使用了约束导致的问题，你在`xib`中对`UITextField`使用了约束，每当`UITextField`中的内容发生改变，会触发约束相关操作，同时触发上层的`viewDidLayoutSubviews`调用。

你可以在你提供的`demo`中，把`UITextField`的约束全部去掉，就不会触发了。或者你可以使用纯代码在`UIViewController`中添加`UITextField`，使用约束来布局，当`UITextField`内容发生改变的时候，也会触发`viewDidLayoutSubviews`。

当强制给`UITextField`固定的位置和大小时，`UITextField`内容发生改变后，还是触发了约束的相关方法，同时触发上层的`viewDidLayoutSubviews`调用，感觉这算是一个坑，至少在`frame`没有发生变化的时候，不应该调用上层方法，`autolayout`还需要优化。

`SegementSlide`中针对这种情况的处理是，在`layoutSegementSlideScrollView`增加了些许判断，不再重复设置或更新约束，同时在`SegementSlideHeaderView`的`config`方法中，会先判断传入的`headerView`是否跟原先的相同，如果相同就不再处理，自然不需要移除旧的`headerView`然后添加新的`headerView`。

你的问题就是因为对`UITextField`使用了约束，每当`UITextField`的内容改变，触发了`viewDidLayoutSubviews`方法，同时调用到了`SegementSlideHeaderView`的`config`方法中，对原有的`headerView`进行了移除并重新添加，导致了每次输入内容，键盘会消失。

**Comment by ascenx** [comment]
> 这是使用了约束导致的问题，你在`xib`中对`UITextField`使用了约束，每当`UITextField`中的内容发生改变，会触发约束相关操作，同时触发上层的`viewDidLayoutSubviews`调用。
> 
> 你可以在你提供的`demo`中，把`UITextField`的约束全部去掉，就不会触发了。或者你可以使用纯代码在`UIViewController`中添加`UITextField`，使用约束来布局，当`UITextField`内容发生改变的时候，也会触发`viewDidLayoutSubviews`。
> 
> 当强制给`UITextField`固定的位置和大小时，`UITextField`内容发生改变后，还是触发了约束的相关方法，同时触发上层的`viewDidLayoutSubviews`调用，感觉这算是一个坑，至少在`frame`没有发生变化的时候，不应该调用上层方法，`autolayout`还需要优化。
> 
> `SegementSlide`中针对这种情况的处理是，在`layoutSegementSlideScrollView`增加了些许判断，不再重复设置或更新约束，同时在`SegementSlideHeaderView`的`config`方法中，会先判断传入的`headerView`是否跟原先的相同，如果相同就不再处理，自然不需要移除旧的`headerView`然后添加新的`headerView`。
> 
> 你的问题就是因为对`UITextField`使用了约束，每当`UITextField`的内容改变，触发了`viewDidLayoutSubviews`方法，同时调用到了`SegementSlideHeaderView`的`config`方法中，对原有的`headerView`进行了移除并重新添加，导致了每次输入内容，键盘会消失。

感谢回答。
