### ISSUE TITLE
偏移重置offset不正确，用户回到初始列表页之后 主动触发滚动才会重置contentOffset为0

### ISSUE THREAD

**Issue by zhangzhengyi12** [Jiar/SegementSlide#51]
## 重现步骤

1. 在 A 列表页滚动到中部
2. 切换到 B 列表页 并滚动到页面头部
3. 这时候重新切换回列表页 A 
4. 这时候A列表页重置的高度不太正常，看上去是类似于header的高度
5. 用户开始触摸滚动的瞬间，重置了ContentOffset 为 0

在example中可以复现，不太稳定，需要多次尝试

## 期望

步骤4的时候 应该直接重置滚动位置为0

**Comment by zhangzhengyi12** [comment]
https://drive.google.com/file/d/1rLmNQ9F_dLgp51-QeR4qs73ljI49xrJ2/view?usp=sharing

录屏

**Comment by Jiar** [comment]
感谢反馈！

我再仔细看下这个问题。

**Comment by Jiar** [comment]
`3.0.1`版本已发布并修复了该问题。
