### ISSUE TITLE
segmentSilde作为JXSegmentedView的子view时，横向滑动问题。

### ISSUE THREAD

**Issue by slash130** [Jiar/SegementSlide#59]
外层是JXSegmentedView，子页面是segmentSilde，在segmentSilde滑动到最左或最右面时怎么把滑动事件切换到外层的JXSegmentedView？

**Comment by Jiar** [comment]
感谢反馈

多层嵌套的意思嘛，目前是没有针对这种场景进行考虑的。

**Comment by Jiar** [comment]
#45
