### ISSUE TITLE
设置 titlesInSwitcher 可以支持 NSAttributedString 或 BadgeView 可以支持自定义就更好了

### ISSUE THREAD

**Issue by alflix** [Jiar/SegementSlide#6]
![screen shot 2019-02-26 at 6 19 51 pm](https://user-images.githubusercontent.com/4870617/53405815-a20b5a80-39f3-11e9-8cc1-62ada0c63e13.png)

hi，如👆这样的页面，如果可以支持 NSAttributedString 就可以实现了。
或者 BadgeView 支持自定义。但是目前 BadgeView 不是特别灵活。

**Comment by Jiar** [comment]
感谢反馈！

目前`SegementSlideSwitcherView`的自定义程度太低，`v2`版本接下来的工作，会让它更加灵活，同时会考虑你提的建议。如果有兴趣，欢迎在测试充分的情况下，在`v2`分支上提供你的`PR`。😋

**Comment by Jiar** [comment]
将`SegementSlide`更新至 2.1 版本，已经让`BadgeView`支持`NSAttributedString`形式的自定义。可以下载最新的`Example`工程查看如何使用这种方式。

@alflix
