### ISSUE TITLE
iOS 14 遇到的问题

### ISSUE THREAD

**Issue by Jayxiang** [Jiar/SegementSlide#63]
先问一下在文件 `SegementSlideHeaderView` 里 `hitTest` 最后为何返回 `delegate.scrollView`？

在 iOS 14 上如果 `segementSlideHeaderView` 返回的是 `UICollectionView`
会导致 cell 无法点击，原因应该被 `hitTest` 拦截了。

**Comment by Jiar** [comment]
感谢反馈

q: `SegementSlideHeaderView` 里 `hitTest` 最后为何返回 `delegate.scrollView`
a: 是为了实现父子`scrollView`实现联动

q: 在 iOS 14 `UICollectionView`的`cell`无法点击
a: 目前需要更多的信息来判断。请问同样的代码，在非 iOS 14 的情况下是否能正常工作呢？

**Comment by Jayxiang** [comment]
1. 没看出哪里需要联动，如果返回 `view`没看到什么问题。
2. 同样的代码在 iOS 14 以下没有问题，因为 `UICollectionViewCell`之前默认有个`UILongPressGestureRecognizer`手势，但是 iOS 14 上并没有，就目前的判断条件无法判断点击的是 `Cell`。

**Comment by Jiar** [comment]
滑动`SegementSlideHeaderView`即能看到联动效果。能否提供一个简易的demo呢？

**Comment by Jayxiang** [comment]
是能看到，但是就算返回 `View`，也没看到异常。
[SegementSlide-master.zip](https://github.com/Jiar/SegementSlide/files/5215640/SegementSlide-master.zip)
demo 很简单，就是`SegementSlideHeaderView `是`UICollectionView`，
可以对比 Xcode 11，和 Xcode 12 beta

**Comment by ali0201** [comment]
我也遇到了。iOS 14以下，是没问题的。

**Comment by Jiar** [comment]
#15 

[reply here](https://github.com/Jiar/SegementSlide/issues/15#issuecomment-719898056)
