### ISSUE TITLE
slideSwitcherView become transparent？

### ISSUE THREAD

**Issue by fsresponser** [Jiar/SegementSlide#7]
let view = UIView()
view.backgroundColor = UIColor.red
slideSwitcherView.superview?.insertSubview(view, belowSubview: slideSwitcherView)

now, slideSwitcherView become transparent？

**Comment by fsresponser** [comment]
![image](https://user-images.githubusercontent.com/8423149/54188409-98511f00-44ea-11e9-83f1-6e83c93209c2.png)

**Comment by Jiar** [comment]
Thanks for feedback!

> let view = UIView()
> view.backgroundColor = UIColor.red
> slideSwitcherView.superview?.insertSubview(view, belowSubview: slideSwitcherView)
> 
> now, slideSwitcherView become transparent？

It's not recommended.

> `segementSlideSwitcherView.layer.zPosition = -1`

This is to make the drop-down refresh control work properly.

**Comment by Jiar** [comment]
A version of V3 is in development, and there is a high probability that the development and release will be completed this week, when the Switcher control will be pulled out to make it easier to use custom controls. 😉
