### ISSUE TITLE
How can I scroll to top?

### ISSUE THREAD

**Issue by HParis** [Jiar/SegementSlide#70]
SegementSlide's version is 3.0.1.

I have a Contoller that inherits SegementSlideDefaultViewController, which has a Header in it. Then I use scrollView.setContentOffset(.zero, animated: true) , but it's ineffective

**Comment by Jiar** [comment]
Thanks for your feedback!

The `SegementSlideDefaultViewController's scrollView` is the root scrollView, try to use the each `subController's scrollView` replace.
