### ISSUE TITLE
SwitcherView如何取消吸底

### ISSUE THREAD

**Issue by ameue** [Jiar/SegementSlide#76]
当header的高度超过屏幕高度时，页面滚动到最顶部的时候，发现SwitcherView吸附在屏幕底部。可以取消这个吸底的效果吗，应该如何取消

**Comment by ameue** [comment]
通过修改switcherView.layer.zPosition层级改低了，可以让header挡住switcherView。但是效果不是很舒服。

**Comment by davuthdv** [comment]
I got the same issue too. Did you manage to find the solution other than changing the zPosition?

**Comment by ameue** [comment]
> I got the same issue too. Did you manage to find the solution other than changing the zPosition?

暂时没有深究

**Comment by davuthdv** [comment]
Ah, ok! Thanks for your reply. I also can't find any other solutions.

**Comment by meilbn** [comment]
注释掉 SegementSlideViewController+setup.swift 文件中的第16行：
edgesForExtendedLayout = []

你就会发现，switcherView 不会吸底了，前提是父类不是 TransparentSlideDefaultViewController，试过 SegementSlideDefaultViewController 没问题。

TransparentSlideViewController.swift 第72行：
edgesForExtendedLayout = .top
改成
edgesForExtendedLayout = [.top, .bottom]
也可以取消吸底

**Comment by ameue** [comment]
我试了下在SegementSlideViewController子类的viewDidLoad中添加下面这句话：
edgesForExtendedLayout = [.bottom]
就可以不吸底了。
不需要去改源码了
@davuthdv

**Comment by meilbn** [comment]
这样也可以，我是改了源码的其他东西，比如headerView里面左右滑动会有上下滑动效果
